// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
)

// SSMGetParamAPI is an autogenerated mock type for the SSMGetParamAPI type
type SSMGetParamAPI struct {
	mock.Mock
}

type SSMGetParamAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SSMGetParamAPI) EXPECT() *SSMGetParamAPI_Expecter {
	return &SSMGetParamAPI_Expecter{mock: &_m.Mock}
}

// GetParameter provides a mock function with given fields: c, params, optFns
func (_m *SSMGetParamAPI) GetParameter(c context.Context, params *ssm.GetParameterInput, optFns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, c, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetParameter")
	}

	var r0 *ssm.GetParameterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) (*ssm.GetParameterOutput, error)); ok {
		return rf(c, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) *ssm.GetParameterOutput); ok {
		r0 = rf(c, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParameterOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) error); ok {
		r1 = rf(c, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SSMGetParamAPI_GetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameter'
type SSMGetParamAPI_GetParameter_Call struct {
	*mock.Call
}

// GetParameter is a helper method to define mock.On call
//   - c context.Context
//   - params *ssm.GetParameterInput
//   - optFns ...func(*ssm.Options)
func (_e *SSMGetParamAPI_Expecter) GetParameter(c interface{}, params interface{}, optFns ...interface{}) *SSMGetParamAPI_GetParameter_Call {
	return &SSMGetParamAPI_GetParameter_Call{Call: _e.mock.On("GetParameter",
		append([]interface{}{c, params}, optFns...)...)}
}

func (_c *SSMGetParamAPI_GetParameter_Call) Run(run func(c context.Context, params *ssm.GetParameterInput, optFns ...func(*ssm.Options))) *SSMGetParamAPI_GetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*ssm.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*ssm.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*ssm.GetParameterInput), variadicArgs...)
	})
	return _c
}

func (_c *SSMGetParamAPI_GetParameter_Call) Return(_a0 *ssm.GetParameterOutput, _a1 error) *SSMGetParamAPI_GetParameter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SSMGetParamAPI_GetParameter_Call) RunAndReturn(run func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) (*ssm.GetParameterOutput, error)) *SSMGetParamAPI_GetParameter_Call {
	_c.Call.Return(run)
	return _c
}

// NewSSMGetParamAPI creates a new instance of SSMGetParamAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSSMGetParamAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SSMGetParamAPI {
	mock := &SSMGetParamAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
